# Generated by Django 4.2.1 on 2023-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_productcategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="resources/images"
            ),
        ),
    ]
