# Generated by Django 4.2.1 on 2023-05-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(null=True, upload_to="static/images"),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(null=True, to="home.productcategory"),
        ),
    ]
