# Generated by Django 4.2.1 on 2023-05-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_product_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="purchase_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
