# Generated by Django 4.2.1 on 2023-09-11 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_product_code_alter_product_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.productmodel",
            ),
        ),
    ]
