# Generated by Django 4.2.1 on 2023-09-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="continue_url",
            field=models.CharField(default="localhost:8080"),
        ),
    ]
