# Generated by Django 4.2.1 on 2023-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_alter_client_email_alter_client_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="unique_code",
            field=models.PositiveIntegerField(verbose_name="unique_code"),
        ),
    ]
