# Generated by Django 4.2.1 on 2023-09-14 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_alter_client_unique_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="age",
            field=models.IntegerField(
                default=16,
                validators=[
                    django.core.validators.MinValueValidator(16),
                    django.core.validators.MaxValueValidator(99),
                ],
            ),
        ),
    ]
